services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rsa-api
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - rsa_net
    restart: always

  postgres:
    build:
      context: ./src/databases/docker/postgres
    container_name: rsa-postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    networks:
      - rsa_net
    restart: always

  redis:
    build:
      context: ./src/databases/docker/redis
    container_name: rsa-redis
    env_file:
      - .env
    ports:
      - "6380:6379"
    networks:
      - rsa_net
    restart: always

volumes:
  postgres_data:

networks:
  rsa_net:

