services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rsa-api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - rsa_net
    restart: always

  db:
    image: postgres:16
    container_name: rsa-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5434:5432"
    networks:
      - rsa_net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: rsa-redis
    env_file:
      - .env
    ports:
      - "6380:6379"
    networks:
      - rsa_net
    restart: always
    command: sh -c '
      mkdir -p /usr/local/etc/redis &&
      echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
      echo "requirepass $$REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
      redis-server /usr/local/etc/redis/redis.conf'
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  rsa_net:

