name: RSA CI

on: [push] 

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    environment: rsa-tests

    env:
      POSTGRES__URL: ${{ secrets.POSTGRES__URL }}
      REDIS__URL: ${{ secrets.REDIS__URL }}
      REDIS__TTL: ${{ secrets.REDIS__TTL }}
      API__PREFIX: ${{ secrets.API__PREFIX }}
      AUTH__PRIVATE_KEY_PATH: ${{ secrets.AUTH__PRIVATE_KEY_PATH }}
      AUTH__PUBLIC_KEY_PATH: ${{ secrets.AUTH__PUBLIC_KEY_PATH }}
      AUTH__ALGORITHM: ${{ secrets.AUTH__ALGORITHM }}
      AUTH__ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.AUTH__ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install project
        run: |
          poetry install
      - name: Run tests
        run: |
          poetry run pytest ./src/tests
      - name: Run mypy
        run: |
          poetry run mypy ./
      - name: Run black
        run: |
          poetry run black ./
      
    
      